# Generated by Django 3.2.5 on 2021-07-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('is_in_menu', models.BooleanField()),
            ],
            options={
                'db_table': 'claravanopdorp_page',
            },
        ),
    ]
