# Generated by Django 3.2.5 on 2021-07-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_footersection'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table=None,
        ),
    ]
