# Generated by Django 3.2.5 on 2021-07-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.page'),
            preserve_default=False,
        ),
    ]
