# Generated by Django 3.2.5 on 2021-08-16 19:20

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=django_quill.fields.QuillField(blank=True, default=None),
        ),
    ]
