# Generated by Django 3.2.9 on 2022-03-24 11:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220324_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(base_url='/static', location=None), upload_to=''),
        ),
    ]
