# Generated by Django 3.2.9 on 2022-03-24 11:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_work_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(base_url='/static', location='static'), upload_to=''),
        ),
    ]
