# Generated by Django 3.2.9 on 2022-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_work_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='video',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
