# Generated by Django 3.2.9 on 2022-04-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_work_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.work')),
            ],
        ),
    ]
