# Generated by Django 3.2.9 on 2022-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_workcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='WorkCase',
        ),
    ]
