# Generated by Django 3.2.9 on 2022-04-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20220406_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksection',
            old_name='page',
            new_name='work',
        ),
    ]
