# Generated by Django 3.2.9 on 2022-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_page_worksection_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksection',
            name='feet',
            field=models.TextField(blank=True),
        ),
    ]
