# Generated by Django 3.2.9 on 2022-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20220407_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyicons',
            name='works',
            field=models.ManyToManyField(to='web.Work'),
        ),
    ]
