# Generated by Django 3.2.9 on 2022-04-11 14:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_technologyicons_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksection',
            name='content',
            field=django_quill.fields.QuillField(blank=True, default=None, null=True),
        ),
    ]
