# Generated by Django 3.2.9 on 2022-04-11 14:39

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_worksection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksection',
            name='content',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
    ]
