# Generated by Django 3.2.9 on 2022-04-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_rename_content_technologyicons_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyicons',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='technologyicons',
            name='icon_class',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
