# Generated by Django 3.2.9 on 2022-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
