# Generated by Django 3.2.9 on 2022-04-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20220412_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksection',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
