# Generated by Django 3.2.9 on 2022-06-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_work_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyIconsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('icon_class', models.CharField(blank=True, default='', max_length=64)),
                ('url', models.CharField(blank=True, default='', max_length=256)),
                ('about_icons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.technologyicons')),
            ],
        ),
    ]
