# Generated by Django 3.2.9 on 2022-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_technologyiconsabout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologyiconsabout',
            old_name='about_icons',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='technologyiconsabout',
            name='works',
            field=models.ManyToManyField(to='web.Work'),
        ),
    ]
