# Generated by Django 3.2.9 on 2022-06-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20220601_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='title',
        ),
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='url',
        ),
    ]
