# Generated by Django 3.2.9 on 2022-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20220602_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='works',
        ),
    ]
