# Generated by Django 3.2.9 on 2022-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_remove_technologyiconsabout_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyiconsabout',
            name='works',
            field=models.ManyToManyField(to='web.Work'),
        ),
    ]
