# Generated by Django 3.2.9 on 2022-06-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_technologyiconsabout_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyiconsabout',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='web.technologyicons'),
        ),
    ]
