# Generated by Django 3.2.9 on 2022-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_technologyiconsabout_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='technologyiconsabout',
            name='works',
        ),
        migrations.AddField(
            model_name='technologyiconsabout',
            name='icon_class',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='technologyiconsabout',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='technologyiconsabout',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
