# Generated by Django 3.2.9 on 2022-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_about_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
